using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Runtime.CompilerServices;
using Common.Data;
using Common.Resources;
using CommonDataTypes;
using Microsoft.Xna.Framework;
using TheraEngine.Collections;
using TheraEngine.Helpers;

namespace Common.Game;

public static class WosbNpcs
{
	private struct BossSpecs
	{
		public required NpcType Class;

		public required string Name;

		public required int ShipId;

		public required int Hp;

		public required int Armor;

		public required int Speed;

		public required int DamagePerShot;

		public required int ReloadCannonSec;

		public CannonClass CannonClass;

		public int CannonDistOverride;

		public int? SpecialBalls;

		public required NpcVisualEffect Visual;

		public int? SpecialServerEffect;

		public int? OverrideMortarDamage;

		public int? OverrideCrewCount;

		public required int[] SpawnRegions;

		public required int FleetsPerRegion;

		public int FleetSize;

		public (NpcGenerator, int)[] DefenceWaves;

		public BossSpecs()
		{
			Class = NpcType.Seafarer;
			Name = null;
			ShipId = 0;
			Hp = 0;
			Armor = 0;
			Speed = 0;
			DamagePerShot = 0;
			ReloadCannonSec = 0;
			CannonClass = CannonClass.LiteCannon;
			SpecialBalls = null;
			Visual = NpcVisualEffect.Regular;
			SpecialServerEffect = null;
			OverrideMortarDamage = null;
			OverrideCrewCount = null;
			SpawnRegions = null;
			FleetsPerRegion = 0;
			CannonDistOverride = 0;
			FleetSize = 1;
			DefenceWaves = new(NpcGenerator, int)[0];
		}
	}

	[CompilerGenerated]
	private sealed class _003C_003Ec__DisplayClass17_0
	{
		public WorldMapRegionInfo region;

		internal bool _003CAutogeneratedNpcForMap_003Eb__3(IslePortInfo _007B4088_007D)
		{
			return _007B4088_007D.IsStronghold && _007B4088_007D.NearRegion == region;
		}
	}

	[CompilerGenerated]
	private sealed class _003C_003Ec__DisplayClass18_0
	{
		public IslePortInfo port;

		internal bool _003CAutogeneratedNpcForPort_003Eb__0(PlayerShipInfo _007B4089_007D)
		{
			return ((port.ShallowUpperRang == -1) ? 1 : port.ShallowUpperRang) == _007B4089_007D.Rank && _007B4089_007D.CanBeUsedForNpc;
		}
	}

	[CompilerGenerated]
	private sealed class _003C_003Ec__DisplayClass18_1
	{
		public NpcGenerator output;

		internal bool _003CAutogeneratedNpcForPort_003Eb__2(PlayerShipInfo _007B4090_007D)
		{
			return _007B4090_007D.StaticInfo.ID == output.Ship && _007B4090_007D.CanBeUsedForNpc;
		}
	}

	[CompilerGenerated]
	private sealed class _003CAutogeneratedNpcForMap_003Ed__17 : IEnumerable<NpcGenerator>, IEnumerable, IEnumerator<NpcGenerator>, IEnumerator, IDisposable
	{
		private int _007B4102_007D;

		private NpcGenerator _007B4103_007D;

		private int _007B4104_007D;

		private Sequence _007B4105_007D;

		public Sequence _003C_003E3__srandom;

		private WorldMapRegionInfo _007B4106_007D;

		public WorldMapRegionInfo _003C_003E3__region;

		private _003C_003Ec__DisplayClass17_0 _007B4107_007D;

		private WorldMapRegionInfo _007B4108_007D;

		private float _007B4109_007D;

		private float _007B4110_007D;

		private int _007B4111_007D;

		private bool _007B4112_007D;

		private int _007B4113_007D;

		private float _007B4114_007D;

		private int _007B4115_007D;

		private bool _007B4116_007D;

		private float _007B4117_007D;

		private float _007B4118_007D;

		private int _007B4119_007D;

		private int _007B4120_007D;

		private int _007B4121_007D;

		private int _007B4122_007D;

		private PlayerShipInfo _007B4123_007D;

		private NpcLocation _007B4124_007D;

		private Tlist<NpcGenerator> _007B4125_007D;

		private int _007B4126_007D;

		private int _007B4127_007D;

		private int _007B4128_007D;

		private int _007B4129_007D;

		private NpcLocation _007B4130_007D;

		private NpcLocation _007B4131_007D;

		private int _007B4132_007D;

		private NpcGenerator _007B4133_007D;

		private int _007B4134_007D;

		private NpcGenerator _007B4135_007D;

		private int _007B4136_007D;

		private int _007B4137_007D;

		private NpcGenerator _007B4138_007D;

		private int _007B4139_007D;

		private NpcGenerator _007B4140_007D;

		private int _007B4141_007D;

		private NpcGenerator _007B4142_007D;

		private int _007B4143_007D;

		private NpcGenerator _007B4144_007D;

		private int _007B4145_007D;

		private int _007B4146_007D;

		private NpcGenerator _007B4147_007D;

		private int _007B4148_007D;

		private NpcGenerator _007B4149_007D;

		private int _007B4150_007D;

		private NpcGenerator _007B4151_007D;

		private int _007B4152_007D;

		private NpcGenerator _007B4153_007D;

		private int _007B4154_007D;

		private NpcGenerator _007B4155_007D;

		private int _007B4156_007D;

		private NpcGenerator _007B4157_007D;

		private int _007B4158_007D;

		private int _007B4159_007D;

		private NpcGenerator _007B4160_007D;

		private int _007B4161_007D;

		private int _007B4162_007D;

		private NpcGenerator _007B4163_007D;

		private int _007B4164_007D;

		private NpcGenerator _007B4165_007D;

		private int _007B4166_007D;

		private NpcGenerator _007B4167_007D;

		private int _007B4168_007D;

		private NpcGenerator _007B4169_007D;

		private IEnumerator<NpcGenerator> _007B4170_007D;

		private NpcGenerator _007B4171_007D;

		NpcGenerator IEnumerator<NpcGenerator>.Current
		{
			[DebuggerHidden]
			get
			{
				return _007B4103_007D;
			}
		}

		object IEnumerator.Current
		{
			[DebuggerHidden]
			get
			{
				return _007B4103_007D;
			}
		}

		[DebuggerHidden]
		public _003CAutogeneratedNpcForMap_003Ed__17(int _007B4096_007D)
		{
			_007B4102_007D = _007B4096_007D;
			_007B4104_007D = Environment.CurrentManagedThreadId;
		}

		[DebuggerHidden]
		private void _007B4097_007D()
		{
			int num = _007B4102_007D;
			if (num == -3 || num == 14)
			{
				try
				{
				}
				finally
				{
					_007B4099_007D();
				}
			}
			_007B4107_007D = null;
			_007B4108_007D = null;
			_007B4123_007D = null;
			_007B4124_007D = default(NpcLocation);
			_007B4125_007D = null;
			_007B4130_007D = default(NpcLocation);
			_007B4131_007D = default(NpcLocation);
			_007B4133_007D = null;
			_007B4135_007D = null;
			_007B4138_007D = null;
			_007B4140_007D = null;
			_007B4142_007D = null;
			_007B4144_007D = null;
			_007B4147_007D = null;
			_007B4149_007D = null;
			_007B4151_007D = null;
			_007B4153_007D = null;
			_007B4155_007D = null;
			_007B4157_007D = null;
			_007B4160_007D = null;
			_007B4163_007D = null;
			_007B4165_007D = null;
			_007B4167_007D = null;
			_007B4169_007D = null;
			_007B4170_007D = null;
			_007B4171_007D = null;
			_007B4102_007D = -2;
		}

		void IDisposable.Dispose()
		{
			//ILSpy generated this explicit interface implementation from .override directive in {4097}
			this._007B4097_007D();
		}

		private bool _007B4098_007D()
		{
			//IL_1d5b: Unknown result type (might be due to invalid IL or missing references)
			try
			{
				switch (_007B4102_007D)
				{
				default:
					return false;
				case 0:
					_007B4102_007D = -1;
					_007B4107_007D = new _003C_003Ec__DisplayClass17_0();
					_007B4107_007D.region = _007B4106_007D;
					NpcShipHelper.allShipLimit.Clear();
					_007B4108_007D = Gameplay.WorldMap.RegionsInfo.Last();
					_007B4109_007D = 73f / 85f;
					_007B4110_007D = 1.07f * _007B4107_007D.region.AreaFactor * _007B4109_007D * _007B4109_007D;
					_007B4111_007D = _007B4107_007D.region.LevelInt + 1;
					_007B4112_007D = true;
					_007B4113_007D = (_007B4107_007D.region.Feature.HasFlag(WorldMapRegionInfo.FeatureType.NorthRegion) ? 3 : 0);
					_007B4114_007D = (float)(12 - _007B4111_007D / 3 - _007B4113_007D) * _007B4110_007D;
					_007B4115_007D = _007B4105_007D.Round((float)(4 * ((_007B4107_007D.region == _007B4108_007D) ? 3 : 2)) * _007B4110_007D * 0.88f);
					_007B4132_007D = 0;
					goto IL_0343;
				case 1:
					_007B4102_007D = -1;
					_007B4133_007D = null;
					_007B4132_007D++;
					goto IL_0343;
				case 2:
					_007B4102_007D = -1;
					_007B4135_007D = null;
					_007B4134_007D++;
					goto IL_0616;
				case 3:
					_007B4102_007D = -1;
					_007B4140_007D = null;
					_007B4139_007D++;
					goto IL_0909;
				case 4:
					_007B4102_007D = -1;
					_007B4142_007D = null;
					_007B4141_007D++;
					goto IL_0a65;
				case 5:
					_007B4102_007D = -1;
					_007B4144_007D = null;
					_007B4143_007D++;
					goto IL_0dac;
				case 6:
					_007B4102_007D = -1;
					_007B4149_007D = null;
					_007B4148_007D++;
					goto IL_0f1d;
				case 7:
					_007B4102_007D = -1;
					_007B4151_007D = null;
					_007B4150_007D++;
					goto IL_1052;
				case 8:
					_007B4102_007D = -1;
					_007B4153_007D = null;
					_007B4152_007D++;
					goto IL_119b;
				case 9:
					_007B4102_007D = -1;
					_007B4155_007D = null;
					_007B4154_007D++;
					goto IL_12e6;
				case 10:
					_007B4102_007D = -1;
					_007B4157_007D = null;
					_007B4156_007D++;
					goto IL_161f;
				case 11:
					_007B4102_007D = -1;
					_007B4163_007D = null;
					_007B4161_007D++;
					goto IL_17ac;
				case 12:
					_007B4102_007D = -1;
					_007B4165_007D = null;
					_007B4164_007D++;
					goto IL_191f;
				case 13:
					_007B4102_007D = -1;
					_007B4124_007D = new NpcLocation(_007B2330_007D: true);
					_007B4125_007D = new Tlist<NpcGenerator>();
					_007B4166_007D = 0;
					while (_007B4166_007D < 19)
					{
						_007B4167_007D = new NpcGenerator();
						NpcShipHelper.NpcStatHelper(_007B4105_007D, _007B4167_007D, _007B4107_007D.region, 2 + _007B4105_007D.RangeInt(0, 4), (_007B4166_007D % 2 == 0) ? CannonClass.DistanceCannon : CannonClass.HeavyCannon, false, false, false, false, null, false, ShipClass.Destroyer, ShipClass.Hardship, ShipClass.Battleship, ShipClass.CargoShip, ShipClass.Mortar);
						_007B4167_007D.Hp *= 1.4f;
						_007B4167_007D.Speed += 1f;
						_007B4167_007D.Armor += 1.5f;
						_007B4167_007D.AttackDistance += 10f;
						_007B4167_007D.Name = "Sea Spirit";
						_007B4167_007D.Class = NpcType.Empire_Regular;
						_007B4167_007D.AttackID = ((_007B4166_007D % 3 == 0) ? 500 : 7);
						_007B4167_007D.Generation = 1;
						_007B4167_007D.Location = _007B4124_007D;
						_007B4167_007D.Visual = NpcVisualEffect.ShadowShip;
						_007B4167_007D.SpecialSpawnIntervalMin = 4f;
						_007B4125_007D.Add(in _007B4167_007D);
						_007B4167_007D = null;
						_007B4166_007D++;
					}
					_007B4168_007D = 0;
					while (_007B4168_007D < 12)
					{
						_007B4169_007D = new NpcGenerator();
						NpcShipHelper.NpcStatHelper(_007B4105_007D, _007B4169_007D, _007B4107_007D.region, 2 + _007B4105_007D.RangeInt(0, 5), (_007B4168_007D % 2 == 0) ? CannonClass.DistanceCannon : CannonClass.HeavyCannon, false, false, false, true, null, false, ShipClass.Destroyer, ShipClass.Hardship, ShipClass.Mortar);
						_007B4169_007D.Armor = Math.Max(1f, _007B4169_007D.Armor * 0.5f);
						_007B4169_007D.Speed += 5f;
						_007B4169_007D.Name = "   ";
						_007B4169_007D.Class = NpcType.Fanatics;
						_007B4169_007D.Generation = ((_007B4168_007D <= 8) ? 3 : 2);
						_007B4169_007D.Location = _007B4124_007D;
						_007B4169_007D.Visual = NpcVisualEffect.DestroyedShip;
						_007B4169_007D.SpecialSpawnIntervalMin = 2f;
						_007B4125_007D.Add(in _007B4169_007D);
						_007B4169_007D = null;
						_007B4168_007D++;
					}
					_007B4126_007D = 2;
					_007B4127_007D = 7;
					_007B4128_007D = 9;
					_007B4129_007D = 10;
					_007B4130_007D = new NpcLocation(_007B4107_007D.region);
					_007B4131_007D = new NpcLocation(Gameplay.LegendBossZone[0]);
					BossSpecial(_007B4125_007D, _007B4130_007D, new BossSpecs
					{
						Class = NpcType.Empire_Legendary2l,
						Name = "Green Eye",
						ShipId = 11,
						Hp = 1800,
						Armor = 2,
						Speed = 15,
						DamagePerShot = 70,
						ReloadCannonSec = 7,
						CannonClass = CannonClass.DistanceCannon,
						SpecialBalls = 500,
						Visual = NpcVisualEffect.BloodShip,
						FleetsPerRegion = 2,
						SpawnRegions = new int[3] { 2, 3, 4 }
					});
					BossSpecial(_007B4125_007D, _007B4130_007D, new BossSpecs
					{
						Class = NpcType.Empire_Legendary2l,
						Name = "Flying Ice",
						ShipId = 24,
						Hp = 4800,
						Armor = 9,
						Speed = 16,
						DamagePerShot = 200,
						ReloadCannonSec = 15,
						CannonClass = CannonClass.LiteCannon,
						SpecialBalls = _007B4129_007D,
						Visual = NpcVisualEffect.IceShip,
						FleetsPerRegion = 3,
						SpawnRegions = new int[2] { 3, 6 }
					});
					BossSpecial(_007B4125_007D, _007B4130_007D, new BossSpecs
					{
						Class = NpcType.Empire_Legendary2l,
						Name = "Lighting",
						ShipId = 23,
						Hp = 1700,
						Armor = 3,
						Speed = 23,
						DamagePerShot = 50,
						ReloadCannonSec = 7,
						CannonClass = CannonClass.LiteCannon,
						SpecialBalls = _007B4127_007D,
						Visual = NpcVisualEffect.ShadowShip,
						FleetsPerRegion = 2,
						SpawnRegions = new int[3] { 2, 4, 6 }
					});
					BossSpecial(_007B4125_007D, _007B4130_007D, new BossSpecs
					{
						Class = NpcType.Empire_Legendary2l,
						Name = "Sand Storm",
						ShipId = 34,
						Hp = 4440,
						Armor = 15,
						Speed = 14,
						DamagePerShot = 100,
						ReloadCannonSec = 12,
						CannonClass = CannonClass.LiteCannon,
						Visual = NpcVisualEffect.DirtShip,
						FleetsPerRegion = 2,
						SpawnRegions = new int[4] { 4, 5, 7, 8 },
						DefenceWaves = new(NpcGenerator, int)[1] { (new NpcGenerator
						{
							Name = "Shark",
							Hp = 480f,
							Armor = 5f,
							Mobility = 100f,
							AttackID = -1,
							DamagePerShot = 74.52f,
							ReloadCannonTime = 9000f,
							Speed = 18f,
							Visual = NpcVisualEffect.DirtShip,
							Ship = 6
						}, 2) }
					});
					BossSpecial(_007B4125_007D, _007B4130_007D, new BossSpecs
					{
						Class = NpcType.Empire_Legendary2l,
						Name = "Belian",
						ShipId = 19,
						Hp = 5760,
						Armor = 2,
						Speed = 17,
						DamagePerShot = 250,
						ReloadCannonSec = 15,
						CannonClass = CannonClass.DistanceCannon,
						SpecialBalls = _007B4128_007D,
						Visual = NpcVisualEffect.ShadowShip,
						FleetsPerRegion = 2,
						SpawnRegions = new int[3] { 2, 5, 7 }
					});
					BossSpecial(_007B4125_007D, _007B4130_007D, new BossSpecs
					{
						Class = NpcType.Empire_Legendary2l,
						Name = "Powder God",
						ShipId = 25,
						Hp = 7070,
						Armor = 5,
						Speed = 17,
						DamagePerShot = 140,
						ReloadCannonSec = 6,
						CannonClass = CannonClass.LiteCannon,
						SpecialBalls = _007B4126_007D,
						Visual = NpcVisualEffect.Regular,
						SpecialServerEffect = 2,
						FleetsPerRegion = 1,
						SpawnRegions = new int[2] { 4, 6 }
					});
					if (_007B4107_007D.region.LevelInt == _007B4108_007D.LevelInt)
					{
						BossSpecial(_007B4125_007D, _007B4131_007D, new BossSpecs
						{
							Class = NpcType.Empire_Legendary3l,
							Name = "Chief Privateer",
							OverrideCrewCount = 260,
							Hp = 4000,
							Speed = 14,
							Armor = 5,
							ShipId = 14,
							DamagePerShot = 300,
							ReloadCannonSec = 12,
							CannonDistOverride = 140,
							SpecialBalls = _007B4128_007D,
							Visual = NpcVisualEffect.ShadowShip,
							FleetSize = 3,
							FleetsPerRegion = 2,
							SpawnRegions = new int[1] { 1 }
						});
						BossSpecial(_007B4125_007D, _007B4131_007D, new BossSpecs
						{
							Class = NpcType.Empire_Legendary3l,
							Name = "Horror Of The Seas",
							OverrideCrewCount = 300,
							Hp = 5000,
							Speed = 15,
							Armor = 7,
							ShipId = 40,
							DamagePerShot = 500,
							ReloadCannonSec = 14,
							CannonDistOverride = 150,
							Visual = NpcVisualEffect.ShadowShip,
							FleetSize = 3,
							FleetsPerRegion = 2,
							SpawnRegions = new int[1] { 1 }
						});
						BossSpecial(_007B4125_007D, _007B4131_007D, new BossSpecs
						{
							Class = NpcType.Empire_Legendary3l,
							Name = "Red Fleet",
							OverrideCrewCount = 350,
							Hp = 7500,
							Speed = 14,
							Armor = 8,
							ShipId = 30,
							DamagePerShot = 750,
							ReloadCannonSec = 16,
							CannonDistOverride = 150,
							Visual = NpcVisualEffect.ShadowShip,
							FleetSize = 3,
							FleetsPerRegion = 2,
							SpawnRegions = new int[1] { 1 }
						});
						BossSpecial(_007B4125_007D, _007B4131_007D, new BossSpecs
						{
							Class = NpcType.Empire_Legendary3l,
							Name = "Exole",
							OverrideCrewCount = 400,
							Hp = 10000,
							Speed = 18,
							Armor = 9,
							ShipId = 35,
							DamagePerShot = 1200,
							ReloadCannonSec = 18,
							CannonDistOverride = 160,
							SpecialBalls = _007B4127_007D,
							Visual = NpcVisualEffect.MagmaShip,
							SpecialServerEffect = 2,
							FleetSize = 2,
							FleetsPerRegion = 3,
							SpawnRegions = new int[1] { 1 }
						});
						BossSpecial(_007B4125_007D, _007B4131_007D, new BossSpecs
						{
							Class = NpcType.Empire_Legendary3l,
							Name = "Johny",
							OverrideCrewCount = 470,
							Hp = 15000,
							Speed = 16,
							Armor = 6,
							ShipId = 54,
							DamagePerShot = 500,
							ReloadCannonSec = 12,
							CannonDistOverride = 160,
							SpecialBalls = _007B4126_007D,
							Visual = NpcVisualEffect.ShadowShip,
							SpecialServerEffect = 1,
							FleetSize = 2,
							FleetsPerRegion = 3,
							SpawnRegions = new int[1] { 1 }
						});
						BossSpecial(_007B4125_007D, _007B4131_007D, new BossSpecs
						{
							Class = NpcType.Empire_Legendary3l,
							Name = "Empire Patrol",
							OverrideCrewCount = 480,
							Hp = 15000,
							Speed = 17,
							Armor = 5,
							ShipId = 55,
							DamagePerShot = 600,
							ReloadCannonSec = 10,
							CannonDistOverride = 160,
							SpecialBalls = _007B4128_007D,
							Visual = NpcVisualEffect.MagmaShip,
							FleetSize = 2,
							FleetsPerRegion = 2,
							SpawnRegions = new int[1] { 1 },
							DefenceWaves = new(NpcGenerator, int)[1] { (new NpcGenerator
							{
								Name = "Guard",
								Hp = 2666f,
								Armor = 2f,
								Mobility = 100f,
								AttackID = -1,
								DamagePerShot = 500f,
								ReloadCannonTime = 9000f,
								Speed = 18f,
								Visual = NpcVisualEffect.DirtShip,
								Ship = 12
							}, 3) }
						});
						BossSpecial(_007B4125_007D, _007B4131_007D, new BossSpecs
						{
							Class = NpcType.Empire_Legendary3l,
							Name = "Despando",
							OverrideCrewCount = 570,
							Hp = 35000,
							Speed = 18,
							Armor = 8,
							ShipId = 37,
							DamagePerShot = 800,
							ReloadCannonSec = 8,
							CannonDistOverride = 165,
							SpecialBalls = _007B4127_007D,
							Visual = NpcVisualEffect.BloodShip,
							FleetSize = 1,
							FleetsPerRegion = 2,
							SpawnRegions = new int[1] { 1 }
						});
						BossSpecial(_007B4125_007D, _007B4131_007D, new BossSpecs
						{
							Class = NpcType.Empire_Legendary3l,
							Name = "DRAGON",
							OverrideCrewCount = 620,
							Hp = 45000,
							Speed = 23,
							Armor = 12,
							ShipId = 27,
							DamagePerShot = 700,
							ReloadCannonSec = 5,
							CannonDistOverride = 130,
							SpecialBalls = _007B4128_007D,
							Visual = NpcVisualEffect.MagmaShip,
							FleetSize = 1,
							FleetsPerRegion = 2,
							SpawnRegions = new int[1] { 1 },
							DefenceWaves = new(NpcGenerator, int)[1] { (new NpcGenerator
							{
								Name = "Sea Spirit",
								Hp = 2000f,
								Armor = 4f,
								Mobility = 100f,
								AttackID = -1,
								DamagePerShot = 130f,
								ReloadCannonTime = 9000f,
								Speed = 23f,
								Visual = NpcVisualEffect.DirtShip,
								Ship = 12
							}, 3) }
						});
					}
					_007B4170_007D = ((IEnumerable<NpcGenerator>)_007B4125_007D).GetEnumerator();
					_007B4102_007D = -3;
					break;
				case 14:
					{
						_007B4102_007D = -3;
						_007B4171_007D = null;
						break;
					}
					IL_17ac:
					if (_007B4161_007D < 6)
					{
						_007B4162_007D = _007B4161_007D % 3;
						_007B4163_007D = new NpcGenerator();
						_007B4163_007D.Class = NpcType.HeadHunter;
						_007B4163_007D.Name = _007B4105_007D.Pick(NpcShipHelper.pirateNamesShort);
						NpcShipHelper.NpcStatHelper(_007B4105_007D, _007B4163_007D, _007B4107_007D.region, _007B4107_007D.region.LevelInt, (_007B4161_007D % 2 == 0) ? CannonClass.DistanceCannon : CannonClass.LiteCannon, false, false, true, false, null, false, ShipClass.Battleship, ShipClass.Hardship, ShipClass.CargoShip);
						_007B4163_007D.Generation = 0;
						_007B4163_007D.Hp *= 0.8f + (float)_007B4162_007D * 0.3f;
						_007B4163_007D.DamagePerShot *= 0.8f + (float)_007B4162_007D * 0.3f;
						_007B4163_007D.Speed *= 0.95f + (float)_007B4162_007D * 0.1f;
						_007B4163_007D.Tag = _007B4162_007D;
						_007B4103_007D = _007B4163_007D;
						_007B4102_007D = 11;
						return true;
					}
					if (_007B4107_007D.region.LevelInt >= 2)
					{
						_007B4164_007D = 0;
						goto IL_191f;
					}
					goto IL_1931;
					IL_0dac:
					if (_007B4143_007D < _007B4121_007D)
					{
						_007B4144_007D = new NpcGenerator();
						_007B4144_007D.Class = NpcType.PirateFraction1_Fleet;
						_007B4144_007D.Name = _007B4105_007D.Pick(NpcShipHelper.pirateNamesLong);
						NpcShipHelper.NpcStatHelper(_007B4105_007D, _007B4144_007D, _007B4107_007D.region, Math.Min(_007B4108_007D.LevelInt, _007B4107_007D.region.LevelInt + 2), (!_007B4105_007D.Boolean()) ? CannonClass.DistanceCannon : CannonClass.LiteCannon, true, false, false, false, null, _007B4112_007D, ShipClass.Battleship, ShipClass.Hardship, ShipClass.CargoShip);
						_007B4144_007D.Generation = ((_007B4143_007D != 0) ? 1 : 2);
						_007B4144_007D.Hp = 600 + 600 * _007B4107_007D.region.LevelInt + ((_007B4107_007D.region.LevelInt == 0) ? 200 : 600) * _007B4143_007D;
						_007B4144_007D.DamagePerShot *= 1.2f;
						_007B4144_007D.SpecialSpawnIntervalMin = 4f;
						_007B4145_007D = 2 + _007B4143_007D % 2;
						_007B4144_007D.DefenceWaves = new(NpcGenerator, int)[_007B4145_007D];
						_007B4146_007D = 0;
						while (_007B4146_007D < _007B4145_007D)
						{
							_007B4147_007D = new NpcGenerator();
							_007B4147_007D.Class = NpcType.PirateFraction1_Reinforced;
							NpcShipHelper.NpcStatHelper(_007B4105_007D, _007B4147_007D, _007B4107_007D.region, Math.Max(0, _007B4107_007D.region.LevelInt - 1 - _007B4146_007D % 2), CannonClass.DistanceCannon, true, false, false, false, null, false, ShipClass.Destroyer, ShipClass.Battleship, ShipClass.Mortar);
							_007B4107_007D._003CAutogeneratedNpcForMap_003Eg__PirateFraction1Fitting_007C0(_007B4147_007D);
							_007B4144_007D.DefenceWaves[_007B4146_007D] = (new NpcGenerator
							{
								Armor = _007B4147_007D.Armor,
								DamagePerShot = _007B4147_007D.DamagePerShot,
								AttackID = _007B4147_007D.AttackID,
								ReloadCannonTime = _007B4147_007D.ReloadCannonTime,
								Hp = (int)(_007B4147_007D.Hp * 0.9f),
								Name = "Pirate",
								Ship = _007B4147_007D.Ship,
								Speed = _007B4147_007D.Speed,
								Mobility = _007B4147_007D.Mobility
							}, 1);
							_007B4147_007D = null;
							_007B4146_007D++;
						}
						_007B4107_007D._003CAutogeneratedNpcForMap_003Eg__PirateFraction1Fitting_007C0(_007B4144_007D);
						_007B4103_007D = _007B4144_007D;
						_007B4102_007D = 5;
						return true;
					}
					if (Gameplay.WorldMap.Ports.Any((IslePortInfo _007B4088_007D) => _007B4088_007D.IsStronghold && _007B4088_007D.NearRegion == _007B4107_007D.region))
					{
						_007B4148_007D = 0;
						goto IL_0f1d;
					}
					if (!_007B4116_007D)
					{
						_007B4152_007D = 0;
						goto IL_119b;
					}
					goto IL_1637;
					IL_0909:
					if (_007B4139_007D < (_007B4116_007D ? 10 : 5))
					{
						_007B4140_007D = new NpcGenerator();
						_007B4140_007D.Class = NpcType.PirateFraction1_Regular;
						_007B4140_007D.Name = _007B4105_007D.Pick(NpcShipHelper.pirateNamesShort);
						NpcShipHelper.NpcStatHelper(_007B4105_007D, _007B4140_007D, _007B4107_007D.region, _007B4107_007D.region.LevelInt, (!_007B4105_007D.Boolean()) ? CannonClass.HeavyCannon : CannonClass.LiteCannon, true, true, false, true, null, false, ShipClass.Destroyer, ShipClass.Mortar);
						_007B4140_007D.Generation = _007B4105_007D.Round(_007B4117_007D);
						if (_007B4139_007D % 2 == 0)
						{
							_007B4140_007D.FleetSize = 2;
						}
						if (_007B4107_007D.region.Feature.HasFlag(WorldMapRegionInfo.FeatureType.NorthRegion))
						{
							_007B4140_007D.Hp *= 1.2f;
							_007B4140_007D.DamagePerShot *= 1.1f;
						}
						_007B4107_007D._003CAutogeneratedNpcForMap_003Eg__PirateFraction1Fitting_007C0(_007B4140_007D);
						_007B4103_007D = _007B4140_007D;
						_007B4102_007D = 3;
						return true;
					}
					_007B4141_007D = 0;
					goto IL_0a65;
					IL_0f1d:
					if (_007B4148_007D < 5)
					{
						_007B4149_007D = new NpcGenerator();
						_007B4149_007D.Class = NpcType.Fanatics;
						_007B4149_007D.Name = _007B4105_007D.Pick(NpcShipHelper.horrorNames);
						NpcShipHelper.NpcStatHelper(_007B4105_007D, _007B4149_007D, _007B4107_007D.region, _007B4107_007D.region.LevelInt, (_007B4148_007D % 2 != 0) ? CannonClass.HeavyCannon : CannonClass.LiteCannon, true, true, false, true, null, false, ShipClass.Destroyer, ShipClass.CargoShip);
						_007B4149_007D.Generation = _007B4105_007D.Round(_007B4118_007D);
						if (_007B4148_007D <= 2)
						{
							_007B4149_007D.FleetSize = 2;
						}
						_007B4149_007D.Speed += 1f * _007B4107_007D.region.Level;
						_007B4103_007D = _007B4149_007D;
						_007B4102_007D = 6;
						return true;
					}
					_007B4150_007D = 0;
					goto IL_1052;
					IL_12e6:
					if (_007B4154_007D < _007B4120_007D)
					{
						_007B4155_007D = new NpcGenerator();
						_007B4155_007D.Class = NpcType.PirateFraction2_Reinforced;
						_007B4155_007D.Name = _007B4105_007D.Pick(NpcShipHelper.religiousNames);
						NpcShipHelper.NpcStatHelper(_007B4105_007D, _007B4155_007D, _007B4107_007D.region, _007B4107_007D.region.LevelInt + 1, (_007B4154_007D % 2 == 0) ? CannonClass.DistanceCannon : CannonClass.HeavyCannon, false, true, false, false, null, _007B4112_007D, ShipClass.Hardship, ShipClass.Battleship, ShipClass.Mortar);
						_007B4155_007D.Generation = 1;
						_007B4155_007D.Hp *= 1.1f + 0.2f * _007B4107_007D.region.Level;
						_007B4155_007D.DamagePerShot *= 1.2f;
						_003CAutogeneratedNpcForMap_003Eg__PirateFraction2Fitting_007C17_1(_007B4155_007D);
						_007B4103_007D = _007B4155_007D;
						_007B4102_007D = 9;
						return true;
					}
					_007B4156_007D = 0;
					goto IL_161f;
					IL_0a65:
					if (_007B4141_007D < _007B4119_007D)
					{
						_007B4142_007D = new NpcGenerator();
						_007B4142_007D.Class = NpcType.PirateFraction1_Reinforced;
						_007B4142_007D.Name = _007B4105_007D.Pick(NpcShipHelper.pirateNamesLong);
						NpcShipHelper.NpcStatHelper(_007B4105_007D, _007B4142_007D, _007B4107_007D.region, _007B4107_007D.region.LevelInt + 1, _007B4105_007D.Boolean() ? CannonClass.DistanceCannon : CannonClass.HeavyCannon, false, true, false, false, null, _007B4112_007D, ShipClass.Hardship, ShipClass.Battleship);
						_007B4142_007D.Generation = 1;
						_007B4142_007D.Hp *= 1.1f + 0.2f * _007B4107_007D.region.Level;
						_007B4142_007D.DamagePerShot *= 1.3f;
						_007B4107_007D._003CAutogeneratedNpcForMap_003Eg__PirateFraction1Fitting_007C0(_007B4142_007D);
						_007B4103_007D = _007B4142_007D;
						_007B4102_007D = 4;
						return true;
					}
					_007B4143_007D = 0;
					goto IL_0dac;
					IL_1931:
					_007B4123_007D = Gameplay.PlayersInfo.First((PlayerShipInfo _007B4083_007D) => _007B4083_007D.StaticInfo.IsBalloon);
					_007B4103_007D = new NpcGenerator
					{
						Class = NpcType.SpecialNoReward,
						Armor = _007B4123_007D.PatArmor,
						AttackDistance = 100f,
						CannonsAngle = 1f,
						Hp = _007B4123_007D.PatHealth,
						DamagePerShot = 1f,
						ReloadCannonTime = 1f,
						Mobility = _007B4123_007D.PatMobility,
						Name = "Expedition",
						Ship = _007B4123_007D.StaticInfo.ID,
						Speed = _007B4123_007D.PatSpeed,
						Generation = 1,
						FleetSize = 1,
						Location = new NpcLocation(_007B4107_007D.region)
					};
					_007B4102_007D = 13;
					return true;
					IL_1052:
					if (_007B4150_007D < _007B4120_007D)
					{
						_007B4151_007D = new NpcGenerator();
						_007B4151_007D.Class = NpcType.Fanatics;
						_007B4151_007D.Name = _007B4105_007D.Pick(NpcShipHelper.horrorNames);
						NpcShipHelper.NpcStatHelper(_007B4105_007D, _007B4151_007D, _007B4107_007D.region, _007B4107_007D.region.LevelInt, (_007B4150_007D % 2 == 0) ? CannonClass.DistanceCannon : CannonClass.HeavyCannon, false, true, false, false, null, false, ShipClass.Battleship, ShipClass.Hardship);
						_007B4151_007D.Generation = 1;
						_007B4151_007D.Hp *= 1f + 0.2f * _007B4107_007D.region.Level;
						_007B4151_007D.DamagePerShot *= 1.2f;
						_007B4103_007D = _007B4151_007D;
						_007B4102_007D = 7;
						return true;
					}
					goto IL_1637;
					IL_191f:
					if (_007B4164_007D < 3)
					{
						_007B4165_007D = new NpcGenerator();
						_007B4165_007D.Class = NpcType.NyEventNpc;
						_007B4165_007D.Name = "Sea Elf";
						_007B4165_007D.Generation = _007B4105_007D.Round(_007B4110_007D * 4.5f * 0.8f);
						NpcShipHelper.FillNpcStats(_007B4105_007D, _007B4107_007D.region, _007B4107_007D.region.LevelInt, _007B4165_007D, Gameplay.PlayersInfo[76], (_007B4164_007D % 2 == 0) ? CannonClass.DistanceCannon : CannonClass.LiteCannon);
						_007B4165_007D.Hp = 7500f * (0.75f + 0.5f * _007B4107_007D.region.Level);
						_007B4165_007D.Generation = _007B4105_007D.Round(_007B4118_007D);
						_007B4165_007D.Visual = NpcVisualEffect.IceShip;
						_007B4165_007D.AttackID = 21;
						_007B4103_007D = _007B4165_007D;
						_007B4102_007D = 12;
						return true;
					}
					goto IL_1931;
					IL_1637:
					_007B4161_007D = 0;
					goto IL_17ac;
					IL_161f:
					if (_007B4156_007D < _007B4122_007D)
					{
						_007B4157_007D = new NpcGenerator();
						_007B4157_007D.Class = NpcType.PirateFraction2_Fleet;
						_007B4157_007D.Name = _007B4105_007D.Pick(NpcShipHelper.religiousNames);
						NpcShipHelper.NpcStatHelper(_007B4105_007D, _007B4157_007D, _007B4107_007D.region, Math.Min(_007B4108_007D.LevelInt, _007B4107_007D.region.LevelInt + 2), (_007B4156_007D % 2 != 0) ? CannonClass.DistanceCannon : CannonClass.HeavyCannon, true, false, false, false, null, _007B4112_007D, ShipClass.Battleship, ShipClass.Hardship, ShipClass.CargoShip);
						_007B4157_007D.Generation = ((_007B4156_007D != 0) ? 1 : 2);
						_007B4157_007D.Hp = 600 + 600 * _007B4107_007D.region.LevelInt + ((_007B4107_007D.region.LevelInt == 0) ? 200 : 600) * _007B4156_007D;
						_007B4157_007D.DamagePerShot *= 1.2f;
						_007B4157_007D.SpecialSpawnIntervalMin = 4f;
						_007B4158_007D = 2 + _007B4156_007D % 2;
						_007B4157_007D.DefenceWaves = new(NpcGenerator, int)[_007B4158_007D];
						_007B4159_007D = 0;
						while (_007B4159_007D < _007B4158_007D)
						{
							_007B4160_007D = new NpcGenerator();
							_007B4160_007D.Class = NpcType.PirateFraction2_Reinforced;
							NpcShipHelper.NpcStatHelper(_007B4105_007D, _007B4160_007D, _007B4107_007D.region, Math.Max(0, _007B4107_007D.region.LevelInt - 1 - _007B4159_007D % 2), CannonClass.DistanceCannon, true, false, false, false, null, false, ShipClass.Destroyer, ShipClass.Battleship, ShipClass.Mortar);
							_003CAutogeneratedNpcForMap_003Eg__PirateFraction2Fitting_007C17_1(_007B4160_007D);
							_007B4157_007D.DefenceWaves[_007B4159_007D] = (new NpcGenerator
							{
								Armor = _007B4160_007D.Armor,
								DamagePerShot = _007B4160_007D.DamagePerShot,
								AttackID = _007B4160_007D.AttackID,
								ReloadCannonTime = _007B4160_007D.ReloadCannonTime,
								Hp = (int)(_007B4160_007D.Hp * 0.9f),
								Name = "Pirate",
								Ship = _007B4160_007D.Ship,
								Speed = _007B4160_007D.Speed,
								Mobility = _007B4160_007D.Mobility
							}, 1);
							_007B4160_007D = null;
							_007B4159_007D++;
						}
						_003CAutogeneratedNpcForMap_003Eg__PirateFraction2Fitting_007C17_1(_007B4157_007D);
						_007B4103_007D = _007B4157_007D;
						_007B4102_007D = 10;
						return true;
					}
					goto IL_1637;
					IL_0343:
					if (_007B4132_007D < 5)
					{
						_007B4133_007D = new NpcGenerator();
						_007B4133_007D.Class = NpcType.Trader_Regular;
						_007B4133_007D.Name = _007B4105_007D.Pick(NpcShipHelper.traderNames);
						NpcShipHelper.NpcStatHelper(_007B4105_007D, _007B4133_007D, _007B4107_007D.region, _007B4107_007D.region.LevelInt, (_007B4132_007D % 2 == 0) ? CannonClass.DistanceCannon : CannonClass.LiteCannon, true, true, false, false, null, false, ShipClass.Destroyer, ShipClass.CargoShip);
						_007B4133_007D.Generation = _007B4105_007D.Round(_007B4114_007D);
						_007B4133_007D.Hp *= 0.75f + 0.15f * _007B4107_007D.region.Level;
						_007B4133_007D.DamagePerShot *= 0.9f;
						_007B4133_007D.ReloadCannonTime *= 1.1f;
						_007B4133_007D.FleetSize = 2 + _007B4132_007D % 2;
						if (_007B4107_007D.region.LevelInt == 0)
						{
							_007B4133_007D.FleetSize = Math.Min(_007B4133_007D.FleetSize, 2);
						}
						_007B4103_007D = _007B4133_007D;
						_007B4102_007D = 1;
						return true;
					}
					_007B4134_007D = 0;
					goto IL_0616;
					IL_119b:
					if (_007B4152_007D < 5)
					{
						_007B4153_007D = new NpcGenerator();
						_007B4153_007D.Class = NpcType.PirateFraction2_Regular;
						_007B4153_007D.Name = _007B4105_007D.Pick(NpcShipHelper.religiousNames);
						NpcShipHelper.NpcStatHelper(_007B4105_007D, _007B4153_007D, _007B4107_007D.region, _007B4107_007D.region.LevelInt, (_007B4152_007D % 2 != 0) ? CannonClass.HeavyCannon : CannonClass.LiteCannon, true, true, false, true, null, false, ShipClass.Mortar, ShipClass.CargoShip, ShipClass.CargoShip);
						_007B4153_007D.Generation = _007B4105_007D.Round(_007B4118_007D);
						if (_007B4152_007D % 2 == 0)
						{
							_007B4153_007D.FleetSize = 2;
						}
						_003CAutogeneratedNpcForMap_003Eg__PirateFraction2Fitting_007C17_1(_007B4153_007D);
						_007B4103_007D = _007B4153_007D;
						_007B4102_007D = 8;
						return true;
					}
					_007B4154_007D = 0;
					goto IL_12e6;
					IL_0616:
					if (_007B4134_007D < _007B4115_007D)
					{
						_007B4135_007D = new NpcGenerator();
						_007B4135_007D.Class = NpcType.Trader_Ferryman;
						_007B4135_007D.Name = "Ferryman";
						NpcShipHelper.NpcStatHelper(_007B4105_007D, _007B4135_007D, _007B4107_007D.region, Math.Min(_007B4108_007D.LevelInt, _007B4107_007D.region.LevelInt + 2), (_007B4134_007D % 2 != 0) ? CannonClass.DistanceCannon : CannonClass.LiteCannon, true, false, false, false, null, _007B4112_007D, ShipClass.Battleship, ShipClass.CargoShip);
						_007B4135_007D.Generation = 1;
						_007B4135_007D.Hp = 600 + 600 * _007B4107_007D.region.LevelInt + ((_007B4107_007D.region.LevelInt == 0) ? 200 : 600);
						_007B4135_007D.SpecialSpawnIntervalMin = 4f;
						_007B4136_007D = 2 + _007B4134_007D % 2;
						_007B4135_007D.DefenceWaves = new(NpcGenerator, int)[_007B4136_007D];
						_007B4137_007D = 0;
						while (_007B4137_007D < _007B4136_007D)
						{
							_007B4138_007D = new NpcGenerator();
							_007B4138_007D.Class = NpcType.Trader_Regular;
							NpcShipHelper.NpcStatHelper(_007B4105_007D, _007B4138_007D, _007B4107_007D.region, _007B4107_007D.region.LevelInt / 2 + 1, CannonClass.DistanceCannon, true, false, false, false, null, false, ShipClass.Destroyer, ShipClass.CargoShip);
							_007B4135_007D.DefenceWaves[_007B4137_007D] = (new NpcGenerator
							{
								Armor = _007B4138_007D.Armor,
								DamagePerShot = _007B4138_007D.DamagePerShot,
								AttackID = _007B4138_007D.AttackID,
								ReloadCannonTime = _007B4138_007D.ReloadCannonTime,
								Hp = (int)(_007B4138_007D.Hp * 0.9f),
								Name = "Privateer",
								Ship = _007B4138_007D.Ship,
								Speed = _007B4138_007D.Speed,
								Mobility = _007B4138_007D.Mobility
							}, 1);
							_007B4138_007D = null;
							_007B4137_007D++;
						}
						_007B4103_007D = _007B4135_007D;
						_007B4102_007D = 2;
						return true;
					}
					_007B4116_007D = _007B4107_007D.region.LevelInt <= 2;
					_007B4117_007D = 0.5f * (float)(12 - _007B4111_007D / 3 + ((_007B4111_007D == 1) ? 4 : ((_007B4111_007D == 2) ? 1 : 0)) + _007B4113_007D / 2) * _007B4110_007D * 0.88f;
					_007B4118_007D = 0.5f * (float)(12 - _007B4111_007D / 3 + ((_007B4111_007D == 1) ? 3 : 0)) * _007B4110_007D * 0.88f;
					_007B4119_007D = _007B4105_007D.Round(1.4f * (float)(9 - _007B4111_007D / 3) * (float)((!_007B4116_007D) ? 1 : 2) * _007B4107_007D.region.AreaFactor);
					_007B4120_007D = _007B4105_007D.Round(1.4f * (float)(9 - _007B4111_007D / 3) * _007B4107_007D.region.AreaFactor);
					_007B4121_007D = _007B4105_007D.Round(3f * (float)((!_007B4116_007D) ? 1 : 2) * _007B4107_007D.region.AreaFactor);
					_007B4122_007D = _007B4105_007D.Round(3f * _007B4107_007D.region.AreaFactor);
					_007B4139_007D = 0;
					goto IL_0909;
				}
				if (_007B4170_007D.MoveNext())
				{
					_007B4171_007D = _007B4170_007D.Current;
					_007B4103_007D = _007B4171_007D;
					_007B4102_007D = 14;
					return true;
				}
				_007B4099_007D();
				_007B4170_007D = null;
				return false;
			}
			catch
			{
				//try-fault
				_007B4097_007D();
				throw;
			}
		}

		bool IEnumerator.MoveNext()
		{
			//ILSpy generated this explicit interface implementation from .override directive in {4098}
			return this._007B4098_007D();
		}

		private void _007B4099_007D()
		{
			_007B4102_007D = -1;
			if (_007B4170_007D != null)
			{
				_007B4170_007D.Dispose();
			}
		}

		[DebuggerHidden]
		private void _007B4100_007D()
		{
			throw new NotSupportedException();
		}

		void IEnumerator.Reset()
		{
			//ILSpy generated this explicit interface implementation from .override directive in {4100}
			this._007B4100_007D();
		}

		[DebuggerHidden]
		IEnumerator<NpcGenerator> IEnumerable<NpcGenerator>.GetEnumerator()
		{
			_003CAutogeneratedNpcForMap_003Ed__17 _003CAutogeneratedNpcForMap_003Ed__;
			if (_007B4102_007D == -2 && _007B4104_007D == Environment.CurrentManagedThreadId)
			{
				_007B4102_007D = 0;
				_003CAutogeneratedNpcForMap_003Ed__ = this;
			}
			else
			{
				_003CAutogeneratedNpcForMap_003Ed__ = new _003CAutogeneratedNpcForMap_003Ed__17(0);
			}
			_003CAutogeneratedNpcForMap_003Ed__._007B4105_007D = _003C_003E3__srandom;
			_003CAutogeneratedNpcForMap_003Ed__._007B4106_007D = _003C_003E3__region;
			return _003CAutogeneratedNpcForMap_003Ed__;
		}

		[DebuggerHidden]
		private IEnumerator _007B4101_007D()
		{
			return ((IEnumerable<NpcGenerator>)this).GetEnumerator();
		}

		IEnumerator IEnumerable.GetEnumerator()
		{
			//ILSpy generated this explicit interface implementation from .override directive in {4101}
			return this._007B4101_007D();
		}
	}

	[CompilerGenerated]
	private sealed class _003CAutogeneratedNpcForPort_003Ed__18 : IEnumerable<NpcGenerator>, IEnumerable, IEnumerator<NpcGenerator>, IEnumerator, IDisposable
	{
		private int _007B4179_007D;

		private NpcGenerator _007B4180_007D;

		private int _007B4181_007D;

		private Sequence _007B4182_007D;

		public Sequence _003C_003E3__srandom;

		private IslePortInfo _007B4183_007D;

		public IslePortInfo _003C_003E3__port;

		private _003C_003Ec__DisplayClass18_0 _007B4184_007D;

		private WorldMapRegionInfo _007B4185_007D;

		private int _007B4186_007D;

		private float _007B4187_007D;

		private IEnumerator<FractionID> _007B4188_007D;

		private FractionID _007B4189_007D;

		private bool _007B4190_007D;

		private int _007B4191_007D;

		private _003C_003Ec__DisplayClass18_1 _007B4192_007D;

		private FractionID? _007B4193_007D;

		private PlayerShipInfo _007B4194_007D;

		private int _007B4195_007D;

		private float _007B4196_007D;

		private int _007B4197_007D;

		private NpcGenerator _007B4198_007D;

		private int _007B4199_007D;

		private int _007B4200_007D;

		private NpcGenerator _007B4201_007D;

		NpcGenerator IEnumerator<NpcGenerator>.Current
		{
			[DebuggerHidden]
			get
			{
				return _007B4180_007D;
			}
		}

		object IEnumerator.Current
		{
			[DebuggerHidden]
			get
			{
				return _007B4180_007D;
			}
		}

		[DebuggerHidden]
		public _003CAutogeneratedNpcForPort_003Ed__18(int _007B4173_007D)
		{
			_007B4179_007D = _007B4173_007D;
			_007B4181_007D = Environment.CurrentManagedThreadId;
		}

		[DebuggerHidden]
		private void _007B4174_007D()
		{
			int num = _007B4179_007D;
			if (num == -3 || num == 1)
			{
				try
				{
				}
				finally
				{
					_007B4176_007D();
				}
			}
			_007B4184_007D = null;
			_007B4185_007D = null;
			_007B4188_007D = null;
			_007B4192_007D = null;
			_007B4194_007D = null;
			_007B4198_007D = null;
			_007B4201_007D = null;
			_007B4179_007D = -2;
		}

		void IDisposable.Dispose()
		{
			//ILSpy generated this explicit interface implementation from .override directive in {4174}
			this._007B4174_007D();
		}

		private bool _007B4175_007D()
		{
			//IL_0547: Unknown result type (might be due to invalid IL or missing references)
			//IL_0551: Unknown result type (might be due to invalid IL or missing references)
			//IL_0722: Unknown result type (might be due to invalid IL or missing references)
			//IL_072c: Unknown result type (might be due to invalid IL or missing references)
			//IL_03ea: Unknown result type (might be due to invalid IL or missing references)
			//IL_03f4: Unknown result type (might be due to invalid IL or missing references)
			try
			{
				switch (_007B4179_007D)
				{
				default:
					return false;
				case 0:
					_007B4179_007D = -1;
					_007B4184_007D = new _003C_003Ec__DisplayClass18_0();
					_007B4184_007D.port = _007B4183_007D;
					if (!_007B4184_007D.port.AllowCapture)
					{
						break;
					}
					_007B4185_007D = Gameplay.WorldMap.RegionsInfo.Last();
					_007B4186_007D = _007B4184_007D.port.NearRegion.LevelInt;
					_007B4187_007D = Gameplay.PlayersInfo.Where((PlayerShipInfo _007B4089_007D) => ((_007B4184_007D.port.ShallowUpperRang == -1) ? 1 : _007B4184_007D.port.ShallowUpperRang) == _007B4089_007D.Rank && _007B4089_007D.CanBeUsedForNpc).Average((Func<PlayerShipInfo, float>)((PlayerShipInfo _007B4084_007D) => _007B4084_007D.AssotiatedHazardZoneLevel));
					_007B4186_007D = (int)Math.Max(_007B4186_007D, _007B4187_007D);
					_007B4188_007D = FractionDecorator.Nations.Concat(new FractionID[1] { FractionID.None }).GetEnumerator();
					_007B4179_007D = -3;
					goto IL_045e;
				case 1:
					_007B4179_007D = -3;
					_007B4192_007D = null;
					_007B4194_007D = null;
					goto IL_0439;
				case 2:
					_007B4179_007D = -1;
					_007B4198_007D = null;
					_007B4197_007D++;
					goto IL_060f;
				case 3:
					{
						_007B4179_007D = -1;
						_007B4201_007D = null;
						_007B4200_007D++;
						goto IL_07e7;
					}
					IL_0439:
					_007B4191_007D++;
					goto IL_044b;
					IL_07e7:
					if (_007B4200_007D < 3)
					{
						_007B4201_007D = new NpcGenerator();
						NpcShipHelper.NpcStatHelper(_007B4182_007D, _007B4201_007D, _007B4184_007D.port.NearRegion, Math.Min(_007B4185_007D.LevelInt, _007B4186_007D + 1), (_007B4200_007D != 0) ? ((_007B4200_007D == 1) ? CannonClass.DistanceCannon : ((_007B4200_007D != 2) ? CannonClass.DistanceCannon : CannonClass.HeavyCannon)) : CannonClass.LiteCannon, _007B3838_007D: false, _007B3839_007D: false, _007B3840_007D: false, _007B3841_007D: false, null, _007B3843_007D: false, (_007B4200_007D != 0) ? ((_007B4200_007D == 1) ? new ShipClass[1] : ((_007B4200_007D != 2) ? new ShipClass[1] { ShipClass.Battleship } : new ShipClass[1] { ShipClass.Hardship })) : new ShipClass[1] { ShipClass.Mortar });
						_007B4201_007D.Class = NpcType.Empire_Invasion;
						_007B4201_007D.Name = _007B4182_007D.Pick(NpcShipHelper.legendNames);
						_007B4201_007D.Location = new NpcLocation(new Vector3(_007B4184_007D.port.FortPosition, Gameplay.NpcSpawnGuildPatrolRadiusOfFort));
						_007B4201_007D.Visual = NpcVisualEffect.ShadowShip;
						_007B4201_007D.Generation = 0;
						_007B4201_007D.Hp *= 1.4f;
						_007B4201_007D.DamagePerShot *= 1.2f;
						_007B4201_007D.ReloadCannonTime *= 0.9f;
						_007B4201_007D.Mobility *= 1.1f;
						_007B4180_007D = _007B4201_007D;
						_007B4179_007D = 3;
						return true;
					}
					_007B4185_007D = null;
					break;
					IL_045e:
					if (_007B4188_007D.MoveNext())
					{
						_007B4189_007D = _007B4188_007D.Current;
						_007B4190_007D = true;
						_007B4191_007D = 0;
						goto IL_044b;
					}
					_007B4176_007D();
					_007B4188_007D = null;
					_007B4197_007D = 0;
					goto IL_060f;
					IL_044b:
					if (_007B4191_007D < 3)
					{
						_007B4192_007D = new _003C_003Ec__DisplayClass18_1();
						_007B4193_007D = ((_007B4189_007D == FractionID.None) ? ((FractionID?)null) : new FractionID?(_007B4189_007D));
						_007B4193_007D = null;
						_007B4192_007D.output = new NpcGenerator();
						NpcShipHelper.NpcStatHelper(_007B4182_007D, _007B4192_007D.output, _007B4184_007D.port.NearRegion, _007B4186_007D, (_007B4191_007D != 0) ? CannonClass.Bombardier : CannonClass.LiteCannon, false, false, _007B4190_007D, false, _007B4193_007D, false, ShipClass.Battleship, ShipClass.CargoShip, ShipClass.Hardship);
						_007B4194_007D = Gameplay.PlayersInfo.First((PlayerShipInfo _007B4090_007D) => _007B4090_007D.StaticInfo.ID == _007B4192_007D.output.Ship && _007B4090_007D.CanBeUsedForNpc);
						_007B4195_007D = _007B4184_007D.port.ShallowUpperRang;
						if (7 - _007B4184_007D.port.NearRegion.LevelInt - _007B4195_007D > 4)
						{
							_007B4195_007D = Math.Max(_007B4195_007D + 1, 2);
						}
						if (_007B4194_007D.Rank < _007B4195_007D - 1)
						{
							_007B4186_007D--;
							_007B4191_007D--;
							goto IL_0439;
						}
						_007B4192_007D.output.Hp *= 1.2f;
						_007B4192_007D.output.Armor += 1f;
						if (_007B4192_007D.output.DamagePerShot > 600f)
						{
							_007B4192_007D.output.DamagePerShot *= 0.75f;
						}
						_007B4196_007D = 1.25f;
						_007B4192_007D.output.Generation = (int)((float)((_007B4191_007D == 0) ? 1 : 2) + (float)((_007B4191_007D != 2 && Gameplay.IsInHazardZone(in _007B4184_007D.port.EntryPos)) ? 1 : 0) * _007B4196_007D);
						_007B4192_007D.output.SpecialSpawnIntervalMin = 3f;
						_007B4192_007D.output.Class = NpcType.PortPatrol;
						_007B4192_007D.output.Tag = _007B4189_007D;
						_007B4192_007D.output.Name = "Patrol";
						_007B4192_007D.output.Location = new NpcLocation(new Vector3(_007B4184_007D.port.FortPosition, Gameplay.NpcSpawnGuildPatrolRadiusOfFort));
						_007B4180_007D = _007B4192_007D.output;
						_007B4179_007D = 1;
						return true;
					}
					goto IL_045e;
					IL_060f:
					if (_007B4197_007D < 1)
					{
						_007B4198_007D = new NpcGenerator();
						_007B4199_007D = ((_007B4186_007D <= 1) ? 12 : ((_007B4186_007D <= 3) ? 14 : ((_007B4186_007D <= 5) ? 35 : 62)));
						NpcShipHelper.FillNpcStats(_007B4182_007D, _007B4184_007D.port.NearRegion, Math.Min(_007B4185_007D.LevelInt, _007B4186_007D + 1), _007B4198_007D, Gameplay.PlayersInfo[_007B4199_007D], CannonClass.DistanceCannon);
						_007B4198_007D.Class = NpcType.Empire_Invasion;
						_007B4198_007D.Name = _007B4182_007D.Pick(NpcShipHelper.legendNames);
						_007B4198_007D.Location = new NpcLocation(new Vector3(_007B4184_007D.port.FortPosition, Gameplay.NpcSpawnGuildPatrolRadiusOfFort));
						_007B4198_007D.Visual = NpcVisualEffect.ShadowShip;
						_007B4198_007D.Generation = 0;
						_007B4198_007D.Hp *= 2.5f;
						_007B4198_007D.DamagePerShot *= 1.2f;
						_007B4198_007D.ReloadCannonTime *= 0.9f;
						_007B4198_007D.Mobility *= 1.1f;
						_007B4180_007D = _007B4198_007D;
						_007B4179_007D = 2;
						return true;
					}
					_007B4200_007D = 0;
					goto IL_07e7;
				}
				return false;
			}
			catch
			{
				//try-fault
				_007B4174_007D();
				throw;
			}
		}

		bool IEnumerator.MoveNext()
		{
			//ILSpy generated this explicit interface implementation from .override directive in {4175}
			return this._007B4175_007D();
		}

		private void _007B4176_007D()
		{
			_007B4179_007D = -1;
			if (_007B4188_007D != null)
			{
				_007B4188_007D.Dispose();
			}
		}

		[DebuggerHidden]
		private void _007B4177_007D()
		{
			throw new NotSupportedException();
		}

		void IEnumerator.Reset()
		{
			//ILSpy generated this explicit interface implementation from .override directive in {4177}
			this._007B4177_007D();
		}

		[DebuggerHidden]
		IEnumerator<NpcGenerator> IEnumerable<NpcGenerator>.GetEnumerator()
		{
			_003CAutogeneratedNpcForPort_003Ed__18 _003CAutogeneratedNpcForPort_003Ed__;
			if (_007B4179_007D == -2 && _007B4181_007D == Environment.CurrentManagedThreadId)
			{
				_007B4179_007D = 0;
				_003CAutogeneratedNpcForPort_003Ed__ = this;
			}
			else
			{
				_003CAutogeneratedNpcForPort_003Ed__ = new _003CAutogeneratedNpcForPort_003Ed__18(0);
			}
			_003CAutogeneratedNpcForPort_003Ed__._007B4182_007D = _003C_003E3__srandom;
			_003CAutogeneratedNpcForPort_003Ed__._007B4183_007D = _003C_003E3__port;
			return _003CAutogeneratedNpcForPort_003Ed__;
		}

		[DebuggerHidden]
		private IEnumerator _007B4178_007D()
		{
			return ((IEnumerable<NpcGenerator>)this).GetEnumerator();
		}

		IEnumerator IEnumerable.GetEnumerator()
		{
			//ILSpy generated this explicit interface implementation from .override directive in {4178}
			return this._007B4178_007D();
		}
	}

	[CompilerGenerated]
	private sealed class _003CEducationMapNpcs_003Ed__16 : IEnumerable<NpcGenerator>, IEnumerable, IEnumerator<NpcGenerator>, IEnumerator, IDisposable
	{
		private int _007B4208_007D;

		private NpcGenerator _007B4209_007D;

		private int _007B4210_007D;

		NpcGenerator IEnumerator<NpcGenerator>.Current
		{
			[DebuggerHidden]
			get
			{
				return _007B4209_007D;
			}
		}

		object IEnumerator.Current
		{
			[DebuggerHidden]
			get
			{
				return _007B4209_007D;
			}
		}

		[DebuggerHidden]
		public _003CEducationMapNpcs_003Ed__16(int _007B4203_007D)
		{
			_007B4208_007D = _007B4203_007D;
			_007B4210_007D = Environment.CurrentManagedThreadId;
		}

		[DebuggerHidden]
		private void _007B4204_007D()
		{
			_007B4208_007D = -2;
		}

		void IDisposable.Dispose()
		{
			//ILSpy generated this explicit interface implementation from .override directive in {4204}
			this._007B4204_007D();
		}

		private bool _007B4205_007D()
		{
			switch (_007B4208_007D)
			{
			default:
				return false;
			case 0:
				_007B4208_007D = -1;
				_007B4209_007D = new NpcGenerator
				{
					Name = "Coastal Ripper",
					Class = NpcType.SpecialNoReward,
					Location = default(NpcLocation),
					Hp = 840f,
					Armor = 3f,
					AttackDistance = 135f,
					AttackID = -1,
					DamagePerShot = 150f,
					ReloadCannonTime = 8000f,
					Speed = 13f,
					Ship = 10,
					Mobility = 110f,
					Generation = 1,
					EducationMapScenario = NpcEducationMap.BattleEnemies
				};
				_007B4208_007D = 1;
				return true;
			case 1:
				_007B4208_007D = -1;
				_007B4209_007D = new NpcGenerator
				{
					Name = "Vince Morgan",
					Class = NpcType.SpecialNoReward,
					Location = default(NpcLocation),
					Hp = 1120f,
					Armor = 4f,
					AttackDistance = 135f,
					AttackID = -1,
					DamagePerShot = 240f,
					ReloadCannonTime = 13000f,
					Speed = 12f,
					Ship = 42,
					Mobility = 80f,
					Generation = 1,
					EducationMapScenario = NpcEducationMap.BattleEnemies
				};
				_007B4208_007D = 2;
				return true;
			case 2:
				_007B4208_007D = -1;
				_007B4209_007D = new NpcGenerator
				{
					Name = "Gull Basher",
					Class = NpcType.SpecialNoReward,
					Location = default(NpcLocation),
					Hp = 722f,
					Armor = 2f,
					AttackDistance = 120f,
					AttackID = -1,
					DamagePerShot = 160f,
					ReloadCannonTime = 15000f,
					Speed = 13f,
					Ship = 21,
					Mobility = 110f,
					Generation = 2,
					EducationMapScenario = NpcEducationMap.BattleAllies
				};
				_007B4208_007D = 3;
				return true;
			case 3:
				_007B4208_007D = -1;
				_007B4209_007D = new NpcGenerator
				{
					Name = "Shaving",
					Class = NpcType.SpecialNoReward,
					Location = default(NpcLocation),
					Hp = 552f,
					Armor = 2f,
					AttackDistance = 150f,
					AttackID = -1,
					DamagePerShot = 120f,
					ReloadCannonTime = 9000f,
					Speed = 18f,
					Ship = 11,
					Mobility = 100f,
					Generation = 1,
					EducationMapScenario = NpcEducationMap.BattleAllies
				};
				_007B4208_007D = 4;
				return true;
			case 4:
				_007B4208_007D = -1;
				_007B4209_007D = new NpcGenerator
				{
					Name = "Red Robber",
					Class = NpcType.SpecialNoReward,
					Location = default(NpcLocation),
					Hp = 440f,
					Armor = 3f,
					AttackDistance = 130f,
					AttackID = -1,
					DamagePerShot = 130f,
					ReloadCannonTime = 11000f,
					Speed = 20f,
					Ship = 6,
					Mobility = 100f,
					Generation = 1,
					EducationMapScenario = NpcEducationMap.BattleAllies
				};
				_007B4208_007D = 5;
				return true;
			case 5:
				_007B4208_007D = -1;
				_007B4209_007D = new NpcGenerator
				{
					Name = "Red Robber",
					Class = NpcType.SpecialNoReward,
					Location = default(NpcLocation),
					Hp = 220f,
					Armor = 3f,
					AttackDistance = 130f,
					AttackID = -1,
					DamagePerShot = 80f,
					ReloadCannonTime = 11000f,
					Speed = 18f,
					Ship = 4,
					Mobility = 100f,
					Generation = 1,
					EducationMapScenario = NpcEducationMap.FirstShip
				};
				_007B4208_007D = 6;
				return true;
			case 6:
				_007B4208_007D = -1;
				_007B4209_007D = new NpcGenerator
				{
					Name = Local.pkeg_7_name,
					Class = NpcType.SpecialNoReward,
					Location = default(NpcLocation),
					Hp = 50f,
					Armor = 2f,
					AttackDistance = 1f,
					AttackID = -1,
					DamagePerShot = 1f,
					ReloadCannonTime = 11000f,
					Speed = 17f,
					Ship = 1,
					Mobility = 100f
				};
				_007B4208_007D = 7;
				return true;
			case 7:
				_007B4208_007D = -1;
				return false;
			}
		}

		bool IEnumerator.MoveNext()
		{
			//ILSpy generated this explicit interface implementation from .override directive in {4205}
			return this._007B4205_007D();
		}

		[DebuggerHidden]
		private void _007B4206_007D()
		{
			throw new NotSupportedException();
		}

		void IEnumerator.Reset()
		{
			//ILSpy generated this explicit interface implementation from .override directive in {4206}
			this._007B4206_007D();
		}

		[DebuggerHidden]
		IEnumerator<NpcGenerator> IEnumerable<NpcGenerator>.GetEnumerator()
		{
			if (_007B4208_007D == -2 && _007B4210_007D == Environment.CurrentManagedThreadId)
			{
				_007B4208_007D = 0;
				return this;
			}
			return new _003CEducationMapNpcs_003Ed__16(0);
		}

		[DebuggerHidden]
		private IEnumerator _007B4207_007D()
		{
			return ((IEnumerable<NpcGenerator>)this).GetEnumerator();
		}

		IEnumerator IEnumerable.GetEnumerator()
		{
			//ILSpy generated this explicit interface implementation from .override directive in {4207}
			return this._007B4207_007D();
		}
	}

	public static bool UnbindCapersWithWorldTravel = false;

	public const int CountOfEmpireShipTypes = 4;

	public static float NpcWantedLevelDiff1 = 0.3f;

	public static float NpcWantedLevelDiff2 = 0.7f;

	public static float NpcWantedLevelDiff3 = 1f;

	public const float WanderingTraderInteropDistance = 35f;

	private static int[] npcTGdrop_Speed = new int[5] { 2, 8, 11, 12, 28 };

	private static int[] npcTGdrop_Armor = new int[5] { 2, 15, 16, 13, 14 };

	private static int[] npcTGdrop_Common = new int[3] { 2, 27, 21 };

	private static int name2x = 0;

	public static int WantedLevelHeadhunterIntervalSec(int _007B4047_007D)
	{
		return (20 - _007B4047_007D * 5) * 60;
	}

	public static float WantedLevelAdd(NpcInfo _007B4048_007D, bool _007B4049_007D)
	{
		return (_007B4049_007D && _007B4048_007D.UseTradingRoute) ? 0.12f : 0f;
	}

	private static GSI allowDropTraderDefault(Vector2 _007B4050_007D)
	{
		//IL_0022: Unknown result type (might be due to invalid IL or missing references)
		return new GSI().Exs(1, 3).Exs(4, 2).Exs(13, 1)
			.Exs(3, 1)
			.Exs(getResIdFromTradingItem(_007B4050_007D), 2);
	}

	internal static GSI allowDropTraderRare()
	{
		return new GSI().Exs(1, 2).Exs(4, 2).Exs(12, 2)
			.Exs(13, 2)
			.Exs(11, 2);
	}

	private static GSI allowDropProvision(Vector2 _007B4051_007D)
	{
		//IL_0005: Unknown result type (might be due to invalid IL or missing references)
		return new GSI().Exs(getResIdFromTradingItem(_007B4051_007D), 4).Exs(2, 1).Exs(21, 1);
	}

	private static int getResIdFromTradingItem(Vector2 _007B4052_007D)
	{
		//IL_001e: Unknown result type (might be due to invalid IL or missing references)
		WorldMapRegionInfo region = Gameplay.GetNearWorldRegion(in _007B4052_007D);
		WorldMapRegionInfo worldMapRegionInfo = Gameplay.WorldMap.RegionsInfo.FindNear(_007B4052_007D, (WorldMapRegionInfo _007B4085_007D) => (Vector2)((_007B4085_007D == region) ? new Vector2(10000f, 0f) : _007B4085_007D.CenterPos));
		for (int num = 0; num < 2; num++)
		{
			ResourceInfo[] array = Gameplay.ItemsInfo.Where((ResourceInfo _007B4086_007D) => _007B4086_007D.IsTradingItem && _007B4086_007D.TradingItemEconomyRegion == region.ItemsEconomyReigion && _007B4086_007D.TradingItemShouldBeInNps).ToArray();
			if (array.Length == 0)
			{
				if (Rand.Chanse(50f))
				{
					region = worldMapRegionInfo;
					continue;
				}
				break;
			}
			return Rand.Pick(array).ID;
		}
		return Rand.Pick<int>(2, 6);
	}

	[IteratorStateMachine(typeof(_003CEducationMapNpcs_003Ed__16))]
	internal static IEnumerable<NpcGenerator> EducationMapNpcs()
	{
		//yield-return decompiler failed: Method not found
		return new _003CEducationMapNpcs_003Ed__16(-2);
	}

	[IteratorStateMachine(typeof(_003CAutogeneratedNpcForMap_003Ed__17))]
	internal static IEnumerable<NpcGenerator> AutogeneratedNpcForMap(Sequence _007B4053_007D, WorldMapRegionInfo _007B4054_007D)
	{
		//yield-return decompiler failed: Method not found
		return new _003CAutogeneratedNpcForMap_003Ed__17(-2)
		{
			_003C_003E3__srandom = _007B4053_007D,
			_003C_003E3__region = _007B4054_007D
		};
	}

	[IteratorStateMachine(typeof(_003CAutogeneratedNpcForPort_003Ed__18))]
	internal static IEnumerable<NpcGenerator> AutogeneratedNpcForPort(Sequence _007B4055_007D, IslePortInfo _007B4056_007D)
	{
		//yield-return decompiler failed: Method not found
		return new _003CAutogeneratedNpcForPort_003Ed__18(-2)
		{
			_003C_003E3__srandom = _007B4055_007D,
			_003C_003E3__port = _007B4056_007D
		};
	}

	private static void BossSpecial(Tlist<NpcGenerator> _007B4057_007D, NpcLocation _007B4058_007D, BossSpecs _007B4059_007D)
	{
		int[] spawnRegions = _007B4059_007D.SpawnRegions;
		foreach (int num in spawnRegions)
		{
			if ((_007B4058_007D.AsWorldRegion != null && num - 1 == _007B4058_007D.AsWorldRegion.LevelInt) || _007B4058_007D.AsWorldZone.HasValue)
			{
				NpcGenerator item = new NpcGenerator
				{
					Name = _007B4059_007D.Name,
					Class = _007B4059_007D.Class,
					Ship = _007B4059_007D.ShipId,
					Hp = _007B4059_007D.Hp,
					Armor = _007B4059_007D.Armor,
					Mobility = 100f,
					DamagePerShot = GetDamageForLocation(_007B4059_007D, _007B4058_007D),
					ReloadCannonTime = _007B4059_007D.ReloadCannonSec * 1000,
					AttackID = (_007B4059_007D.SpecialBalls ?? (-1)),
					AttackDistance = ((_007B4059_007D.CannonDistOverride > 0) ? ((float)_007B4059_007D.CannonDistOverride) : (CommonSupport.CannonDistance(_007B4059_007D.CannonClass) + 10f)),
					Speed = _007B4059_007D.Speed,
					FleetSize = _007B4059_007D.FleetSize,
					Generation = _007B4059_007D.FleetsPerRegion * _007B4059_007D.FleetSize,
					Location = _007B4058_007D,
					Visual = _007B4059_007D.Visual,
					SpecialSpawnIntervalMin = ((_007B4059_007D.Class == NpcType.Empire_Legendary3l) ? 720f : ((_007B4059_007D.Class == NpcType.Empire_Legendary2l) ? 5f : 0.5f)),
					DefenceWaves = _007B4059_007D.DefenceWaves,
					OverrideMortarDamage = _007B4059_007D.OverrideMortarDamage,
					OverrideCrewCount = _007B4059_007D.OverrideCrewCount
				};
				_007B4057_007D.Add(in item);
			}
		}
		if (_007B4059_007D.DefenceWaves.Any(((NpcGenerator, int) _007B4091_007D) => _007B4091_007D.Item1.Speed < (float)(_007B4059_007D.Speed - 1)))
		{
			GameLoader.Current.AddImportant(_007B4059_007D.Name + " has too slow DefenceWaves");
		}
		static float GetDamageForLocation(BossSpecs _007B4078_007D, NpcLocation _007B4079_007D)
		{
			if (_007B4078_007D.Class == NpcType.Empire_Legendary3l)
			{
				return (float)_007B4078_007D.DamagePerShot * 1.1f;
			}
			return ((float)_007B4078_007D.DamagePerShot * 1.25f * 1.35f + (35f + (float)_007B4079_007D.HzLevel * 5f) * ((float)_007B4078_007D.ReloadCannonSec / 8f)) * 1.1f;
		}
	}

	public static int GetDropPowerupItemsFromNpc(NpcInfo _007B4060_007D, ShipDynamicInfo _007B4061_007D)
	{
		if (_007B4060_007D.Location.IsNull || _007B4060_007D.Descritpion == NpcType.SpecialNoReward)
		{
			return -1;
		}
		float num = ((_007B4061_007D == null) ? 0.5f : (_007B4061_007D.firstHP.Summary / _007B4061_007D.MaxHp));
		int num2 = -1;
		if ((num < 0.3f && Rand.Chanse(70f)) || (num < 0.6f && Rand.Chanse(60f)))
		{
			num2 = Rand.Pick<int>(33, 2, 9);
		}
		else if (Rand.Chanse(42f))
		{
			if (_007B4060_007D.ShipProperties.MaxBasicSpeed >= 18f)
			{
				return npcTGdrop_Speed[Rand.RangeInt(0, npcTGdrop_Speed.Length)];
			}
			if (_007B4060_007D.ShipProperties.Armor >= 6f)
			{
				return npcTGdrop_Armor[Rand.RangeInt(0, npcTGdrop_Armor.Length)];
			}
			num2 = npcTGdrop_Common[Rand.RangeInt(0, npcTGdrop_Common.Length)];
		}
		if (num2 == 1 || num2 == 2 || num2 == 8 || num2 == 9 || num2 == 33)
		{
			if (_007B4060_007D.ShipProperties.MaxHp.Value < 1000f)
			{
				if (num2 == 33)
				{
					num2 = 1;
				}
				if (num2 == 2 || num2 == 1)
				{
					num2 = 0;
				}
				if (num2 == 9 || num2 == 8)
				{
					num2 = 7;
				}
			}
			if (_007B4060_007D.ShipProperties.MaxHp.Value < 1600f)
			{
				if (num2 == 33)
				{
					num2 = 1;
				}
				if (num2 == 2)
				{
					num2 = 1;
				}
				if (num2 == 9)
				{
					num2 = 8;
				}
			}
		}
		return num2;
	}

	internal static (int xp, int gold, int maxCannonBalls) MatchBasicReward(NpcInfo _007B4062_007D, bool _007B4063_007D)
	{
		float num = MathF.Pow(1.19f * _007B4062_007D.ShipProperties.MaxHp.Value, 0.97f);
		float maxBasicSpeed = _007B4062_007D.ShipProperties.MaxBasicSpeed;
		float armor = _007B4062_007D.ShipProperties.Armor;
		float damagePerShot = _007B4062_007D.DamagePerShot;
		float reloadCannonTime = _007B4062_007D.ReloadCannonTime;
		float num2 = Gameplay.ComputeBasicBonus(num * 0.69f + 330f, maxBasicSpeed, armor);
		float num3 = damagePerShot / reloadCannonTime * 1000f;
		float num4 = num3 * ((300f + num) / 75f) * 0.85f;
		float num5 = num4 * 2f / 10f;
		int num8;
		float num6;
		float num7;
		switch (_007B4062_007D.Descritpion)
		{
		case NpcType.SpecialNoReward:
			num8 = 0;
			num6 = 0f;
			num7 = 0f;
			break;
		case NpcType.Empire_Legendary2l:
		case NpcType.Empire_Legendary3l:
			num6 = ((num < 2500f) ? 1.1f : 1f) * (_007B4062_007D.Location.IsNull ? 1f : (_007B4062_007D.Location.IsSeamlessSea ? Gameplay.OutsideSeamMultiplier : Gameplay.WorldMapMultiplier));
			num7 = 0.85f;
			num8 = ((!_007B4062_007D.Location.IsNull) ? (45 + _007B4062_007D.Location.HzLevel * 15) : 0);
			if (_007B4062_007D.Descritpion == NpcType.Empire_Legendary3l)
			{
				num6 *= 1.7f;
			}
			break;
		case NpcType.BonusMap:
		case NpcType.BonusMapBoss:
			num6 = Gameplay.DefaultBonusMapMultiplier;
			num7 = 0.9f;
			num8 = 0;
			num5 *= 2f;
			break;
		case NpcType.Empire_Invasion:
			num6 = (_007B4062_007D.Location.IsSeamlessSea ? Gameplay.OutsideSeamMultiplier : Gameplay.WorldMapMultiplier) * 0.7f;
			num7 = 0.56f;
			num8 = 0;
			break;
		default:
			num6 = (_007B4063_007D ? (Gameplay.WorldMapMultiplier * 0.7f) : (_007B4062_007D.Location.IsNull ? 1f : (_007B4062_007D.Location.IsSeamlessSea ? Gameplay.OutsideSeamMultiplier : Gameplay.WorldMapMultiplier)));
			num7 = 0.8f;
			num8 = ((!_007B4062_007D.Location.IsNull) ? (15 + _007B4062_007D.Location.HzLevel * 6) : 0);
			break;
		}
		int item = num8;
		NpcType descritpion = _007B4062_007D.Descritpion;
		bool flag = (uint)(descritpion - 7) <= 1u;
		int num9 = (flag ? 150 : 75);
		if (_007B4062_007D.Descritpion == NpcType.Trader_Regular)
		{
			num6 *= 1.1f;
		}
		int num10 = (int)((float)num9 + num6 * (num2 + num5) * Gameplay.GameSpeed * 0.88f * 0.9f);
		int item2 = (int)((float)num10 * Gameplay.BasicXpInGold * num7 * 0.9f);
		return (xp: item2, gold: num10, maxCannonBalls: item);
	}

	public static (GSI res, int gold) GetReward(Vector2 _007B4064_007D, NpcInfo _007B4065_007D, int _007B4066_007D, TradingRouteInfo _007B4067_007D)
	{
		//IL_037b: Unknown result type (might be due to invalid IL or missing references)
		//IL_02cd: Unknown result type (might be due to invalid IL or missing references)
		//IL_0324: Unknown result type (might be due to invalid IL or missing references)
		//IL_0501: Unknown result type (might be due to invalid IL or missing references)
		int goldBonus = _007B4065_007D.RewardAmount.GoldBonus;
		GSI gSI = new GSI();
		float num = 0f;
		float num2 = Rand.Range(0.9f, 1.1f);
		NpcType descritpion = _007B4065_007D.Descritpion;
		if ((descritpion == NpcType.PirateFraction1_Regular || descritpion == NpcType.PirateFraction2_Regular || descritpion == NpcType.Trader_Regular) ? true : false)
		{
			float num3 = Rand.Pick<float>(0.7f, 0.7f, 0.7f, 0.7f, 0.7f, 0.7f, 1f, 1.6f, 2.6f);
			num2 *= num3;
		}
		if (_007B4065_007D.Descritpion == NpcType.NyEventNpc)
		{
			num = goldBonus / 2;
			gSI[71] = 1;
			gSI[69] = Rand.Round(10f * _007B4065_007D.ShipProperties.MaxHp.Value / 10000f);
		}
		else if (_007B4065_007D.Descritpion == NpcType.HeadHunter)
		{
			float num4 = (float)goldBonus * 0.5f;
			float num5 = (float)goldBonus * 0.1f;
			AddResByCost(gSI, 1, num4 * 0.66f);
			AddResByCost(gSI, 3, num4 * 0.33f);
			num += num5;
		}
		else if (_007B4065_007D.Extras.IsPirate || _007B4065_007D.Descritpion == NpcType.Fanatics)
		{
			if (_007B4065_007D.Extras.IsReinforcedType)
			{
				if (_007B4065_007D.Location.HzLevel > 0)
				{
					gSI[72] += Rand.Round(_007B4065_007D.ShipProperties.MaxHp.Value / 100f);
				}
				else
				{
					AddResByCost(gSI, 1, num2 * (float)goldBonus * 0.33f);
				}
				switch (_007B4065_007D.Descritpion)
				{
				case NpcType.PirateFraction2_Fleet:
					foreach (int item in Rand.PickMany<int>(2, 39, 9, 10, 22, 1))
					{
						AddResByCost(gSI, item, num2 * (float)goldBonus * 0.5f);
					}
					break;
				default:
					AddResByCost(gSI, 24, num2 * (float)goldBonus * 0.8f);
					if (gSI[24] == 0)
					{
						gSI[24] = 1;
					}
					break;
				case NpcType.PirateFraction1_Fleet:
					break;
				}
			}
			else
			{
				int num6 = (_007B4065_007D.Extras.IsPirate ? 74 : 75);
				int num7 = (_007B4065_007D.Extras.IsPirate ? 30 : 40);
				num2 *= 0.9f;
				if (Rand.Chanse(100 / num7 * WosbTreasuryMaps.CountToComplete(num6)))
				{
					gSI[num6]++;
				}
				int _007B4081_007D = allowDropProvision(_007B4064_007D).RandomName();
				AddResByCost(gSI, _007B4081_007D, num2 * 0.3f * (float)goldBonus);
				if (_007B4065_007D.Location.AsWorldRegion != null && _007B4065_007D.Location.AsWorldRegion.Feature.HasFlag(WorldMapRegionInfo.FeatureType.NorthRegion))
				{
					_007B4081_007D = allowDropTraderDefault(_007B4064_007D).RandomName();
					AddResByCost(gSI, _007B4081_007D, num2 * 0.1f * (float)goldBonus);
				}
				num += 0.7f * (float)goldBonus * num2;
			}
		}
		else if (_007B4065_007D.Extras.IsTrader)
		{
			GSI gSI2 = ((_007B4065_007D.Descritpion == NpcType.Trader_Regular) ? allowDropTraderRare() : allowDropTraderDefault(_007B4064_007D));
			ResourceInfo resourceInfo = ((_007B4067_007D != null && _007B4067_007D.ResourceInfos.Length != 0) ? Rand.Pick(_007B4067_007D.ResourceInfos) : null);
			if (resourceInfo != null)
			{
				gSI2[resourceInfo.ID] += 11;
			}
			ResourceInfo pbsManufacture = Gameplay.WorldMap.GetNearPort(in _007B4064_007D).PbsManufacture;
			if (pbsManufacture != null)
			{
				gSI2[pbsManufacture.ID] += 2;
			}
			float num8 = ((_007B4065_007D.Location.HzLevel == 0) ? 0.33f : 0.25f);
			GSI gSI3;
			if (_007B4065_007D.Descritpion == NpcType.Trader_Ferryman)
			{
				do
				{
					gSI3 = gSI2.Clone().RandomCut(3f);
				}
				while (gSI3.NamesCount != 3);
			}
			else
			{
				int num9 = 73;
				int num10 = 20;
				num2 *= 0.9f;
				if (Rand.Chanse(100 / num10 * WosbTreasuryMaps.CountToComplete(num9)))
				{
					gSI[num9]++;
				}
				gSI3 = gSI2.RandomCut(1f);
				if (resourceInfo != null && gSI3[resourceInfo.ID] == 0)
				{
					gSI3[resourceInfo.ID] = 1;
				}
				else
				{
					int _007B4081_007D2 = (Rand.Chanse(50f) ? 1 : allowDropProvision(_007B4064_007D).RandomName());
					AddResByCost(gSI, _007B4081_007D2, num2 * 0.15f * (float)goldBonus);
				}
			}
			foreach (GSILocalEnumerablePair<ResourceInfo> item2 in (IEnumerable<GSILocalEnumerablePair<ResourceInfo>>)gSI3.ResourceInfo/*cast due to .constrained prefix*/)
			{
				float num11 = item2.Info.MediumCost.Value;
				gSI.Exs(item2.Info.ID, Rand.Round(0.85f * (1f - num8) * num2 / (float)gSI3.NamesCount * (float)goldBonus / num11));
			}
			num += num8 * num2 * (float)goldBonus;
		}
		else
		{
			descritpion = _007B4065_007D.Descritpion;
			if ((uint)(descritpion - 10) <= 1u)
			{
				if (_007B4065_007D.Descritpion == NpcType.Empire_Regular && !_007B4065_007D.IsDefenderOrPrivateer)
				{
					gSI.AddOrRemove(15, Rand.Round((500f + _007B4065_007D.ShipProperties.MaxHp.Value) / 1660f * Gameplay.IncreaseDropOutsideSeam * 0.9f));
				}
				else
				{
					gSI.AddOrRemove(15, (!_007B4065_007D.Location.IsSeamlessSea) ? 1 : Rand.Round(1f * Gameplay.IncreaseDropOutsideSeam));
				}
			}
			else
			{
				descritpion = _007B4065_007D.Descritpion;
				if ((uint)(descritpion - 12) <= 1u)
				{
					float num13;
					if (_007B4065_007D.Descritpion != NpcType.Empire_Legendary2l)
					{
						int num12;
						if (_007B4065_007D.FleetSize != 3)
						{
							if (_007B4065_007D.FleetSize != 2)
							{
								if (_007B4065_007D.FleetSize != 1)
								{
									throw new NotSupportedException();
								}
								num12 = Rand.RangeInt(24, 28);
							}
							else
							{
								num12 = Rand.RangeInt(8, 10);
							}
						}
						else
						{
							num12 = Rand.RangeInt(4, 6);
						}
						num13 = num12;
					}
					else
					{
						num13 = _007B4065_007D.ShipProperties.MaxHp.Value / 3200f;
					}
					float _007B14491_007D = num13;
					gSI[67] += Rand.Round(_007B14491_007D);
					gSI[15] += ((_007B4065_007D.Descritpion == NpcType.Empire_Legendary2l || _007B4065_007D.FleetSize > 1) ? 1 : 4);
					float num14 = num2;
					if (_007B4065_007D.Descritpion == NpcType.Empire_Legendary3l)
					{
						gSI.AddOrRemove(11, Rand.RangeInt(17, 25));
						gSI.AddOrRemove(38, 3);
					}
					else
					{
						int _007B4081_007D3 = allowDropTraderRare().RandomName();
						int num15 = ((_007B4065_007D.Descritpion == NpcType.Empire_Legendary2l) ? 1500 : 5000);
						AddResByCost(gSI, _007B4081_007D3, (float)num15 * 0.9f);
					}
					int value = Gameplay.ItemsInfo.FromID(24).MediumCost.Value;
					if (Rand.Chanse(50f) && goldBonus > value + 200)
					{
						gSI.AddOrRemove(24, 1);
						num14 -= (float)(value / goldBonus);
					}
					if (num14 > 0.3f)
					{
						int _007B4081_007D4 = (Rand.Chanse(50f) ? 1 : 9);
						AddResByCost(gSI, _007B4081_007D4, 0.2f * (float)goldBonus);
						num14 -= 0.2f;
					}
					num += num14 * (float)goldBonus;
				}
				else if (_007B4065_007D.Descritpion == NpcType.PortPatrol)
				{
					AddResByCost(gSI, 1, Rand.Range(0.1f, 0.2f) * (float)goldBonus);
				}
				else if (_007B4065_007D.Descritpion != NpcType.Seafarer)
				{
				}
			}
		}
		if (_007B4065_007D.Location.IsNull)
		{
			num += 20f;
		}
		return (res: gSI, gold: Rand.Round(num));
		static void AddResByCost(GSI _007B4080_007D, int num16, float _007B4082_007D)
		{
			_007B4080_007D[num16] += Rand.Round(_007B4082_007D / (float)Gameplay.ItemsInfo.FromID(num16).MediumCost.Value);
		}
	}

	public static GSI GetCannonBalls(NpcInfo _007B4068_007D, int _007B4069_007D, int _007B4070_007D)
	{
		GSI gSI = new GSI();
		int num;
		if (CalendarEvents.IceBallsDropEnabled && _007B4068_007D.Extras.IsEmpire)
		{
			WorldMapRegionInfo asWorldRegion = _007B4068_007D.Location.AsWorldRegion;
			num = ((asWorldRegion != null && asWorldRegion.Feature == WorldMapRegionInfo.FeatureType.NorthRegion) ? 1 : 0);
		}
		else
		{
			num = 0;
		}
		bool flag = (byte)num != 0;
		if (_007B4068_007D.Descritpion == NpcType.NyEventNpc)
		{
			int num2 = 300;
			gSI[21] += num2;
			return gSI;
		}
		if (_007B4068_007D.Descritpion == NpcType.HeadHunter)
		{
			int num3 = Rand.Round(MathHelper.Lerp(400f, 1500f, (float)_007B4068_007D.Location.HzLevel / 6f));
			gSI[Rand.Chanse(90f) ? Rand.Pick<int>(2, 1) : 7] += num3;
			return gSI;
		}
		if ((Rand.Chanse(50f) || flag) && _007B4068_007D.CountAmmoWillFound != 0)
		{
			int _007B5452_007D = (int)((float)_007B4068_007D.CountAmmoWillFound * Rand.Range(0.85f, 1.25f));
			int num4 = _007B4068_007D.OverrideCannonBalls ?? ((_007B4070_007D == 1 || _007B4070_007D == 2 || _007B4070_007D == 3 || _007B4070_007D == 4) ? _007B4070_007D : Rand.RangeInt(1, 3));
			if (num4 > 7)
			{
				num4 = 1;
			}
			if (flag)
			{
				num4 = 5;
			}
			gSI.AddOrRemove(num4, _007B5452_007D);
		}
		if (_007B4068_007D.EducationMapScenario == NpcEducationMap.FirstShip)
		{
			gSI[2] += 58;
			gSI[3] += 63;
		}
		return gSI;
	}

	public static bool HasCannonsAsLoot(NpcInfo _007B4071_007D)
	{
		return _007B4071_007D.Descritpion == NpcType.PirateFraction1_Fleet;
	}

	public static GSI GetDropCannons(NpcInfo _007B4072_007D, int _007B4073_007D, bool _007B4074_007D)
	{
		int num = 8;
		if (HasCannonsAsLoot(_007B4072_007D))
		{
			IEnumerable<CannonGameInfo> source = Gameplay.CannonsGameInfo.Where(delegate(CannonGameInfo _007B4092_007D)
			{
				bool flag = _007B4072_007D.BasedOn.IsCannonsAllowed(_007B4092_007D.Category) && _007B4092_007D.ID != 1 && _007B4092_007D.ID != 2 && _007B4092_007D.ID != 3;
				bool flag2 = flag;
				if (flag2)
				{
					CannonClass cannonClass = _007B4092_007D.Class;
					bool flag3 = cannonClass <= CannonClass.HeavyCannon;
					flag2 = flag3 || (_007B4092_007D.Class == CannonClass.Mortar && _007B4092_007D.Feature != CannonFeature.Default && _007B4072_007D.MortarShipModification) || (_007B4092_007D.Class == CannonClass.Bombardier && (_007B4072_007D.BasedOn.StaticInfo.FrontSidePorts.Length != 0 || _007B4072_007D.BasedOn.StaticInfo.BackSidePorts.Length != 0));
				}
				return flag2;
			});
			float num2 = 0.1f + _007B4072_007D.ShipProperties.MaxHp.Value / 2300f;
			if (!_007B4074_007D)
			{
				num2 /= 2f;
			}
			float _007B14491_007D = Math.Max(1f, num2);
			GSI gSI = new GSI();
			foreach (CannonGameInfo item in Rand.PickMany(3, source.ToArray()))
			{
				gSI[item.ID] = ((item.Class == CannonClass.Mortar) ? Rand.Round(_007B14491_007D) : Rand.Round(num2));
			}
			return gSI;
		}
		if (_007B4072_007D.Extras.IsBonusMap && _007B4073_007D % 5 == 0)
		{
			float num3 = Math.Min(4f, _007B4072_007D.ShipProperties.MaxHp.Value / 1450f) / 2f;
			if (!_007B4074_007D)
			{
				num3 /= 2f;
			}
			CannonGameInfo cannonGameInfo = null;
			float _007B14491_007D2 = Rand.Range(num3, 2f + num3);
			if (_007B4072_007D.MortarShipModification && Rand.Chanse(num))
			{
				IEnumerable<CannonGameInfo> collection = Gameplay.CannonsGameInfo.Where((CannonGameInfo _007B4093_007D) => _007B4093_007D.Class == CannonClass.Mortar && _007B4093_007D.Poundage.GetValueOrDefault() < (_007B4072_007D.BasedOn.MaxMortarPoundage ?? 100));
				cannonGameInfo = new Tlist<CannonGameInfo>(collection).Rand();
				_007B14491_007D2 = 1f;
			}
			else
			{
				IEnumerable<CannonGameInfo> collection2 = Gameplay.CannonsGameInfo.Where(delegate(CannonGameInfo _007B4094_007D)
				{
					CannonClass cannonClass = _007B4094_007D.Class;
					bool flag = cannonClass <= CannonClass.HeavyCannon;
					return flag && _007B4072_007D.BasedOn.IsCannonsAllowed(_007B4094_007D.Category);
				});
				cannonGameInfo = new Tlist<CannonGameInfo>(collection2).Rand();
			}
			return new GSI().Exs(cannonGameInfo.ID, Rand.Round(_007B14491_007D2));
		}
		return new GSI();
	}

	public static GSI NpcToDestroyResources(NpcInfo _007B4075_007D, in Decorator _007B4076_007D)
	{
		float num = (float)_007B4075_007D.RewardAmount.GoldBonus * 1.3f;
		if (_007B4076_007D.account != null)
		{
			num *= 1f + _007B4076_007D.NpcDecraftBonus;
		}
		GSI gSI = new GSI();
		if (_007B4076_007D.account != null && _007B4076_007D.account.CaptainSkills[PDynamicAccountBonus.PMoreResourcesForDestryingNpc] > 0)
		{
			int _007B5452_007D = (int)MathF.Ceiling(0.5f * num / (float)Gameplay.ItemsInfo.FromID(27).MediumCost.Value);
			gSI.AddOrRemove(27, _007B5452_007D);
		}
		gSI.AddOrRemove(1, (int)(0.45f * num / (float)Gameplay.ItemsInfo.FromID(1).MediumCost.Value));
		gSI.AddOrRemove(20, (int)(0.2f * num / (float)Gameplay.ItemsInfo.FromID(20).MediumCost.Value));
		gSI.AddOrRemove(3, (int)(0.3f * num / (float)Gameplay.ItemsInfo.FromID(3).MediumCost.Value));
		gSI.AddOrRemove(13, (int)(0.15f * num / (float)Gameplay.ItemsInfo.FromID(13).MediumCost.Value));
		return gSI;
	}

	[CompilerGenerated]
	internal static void _003CAutogeneratedNpcForMap_003Eg__PirateFraction2Fitting_007C17_1(NpcGenerator _007B4077_007D)
	{
		_007B4077_007D.Speed -= 2f;
		_007B4077_007D.Armor += 2f;
	}
}
